const {test}=require('node:test');const assert=require('node:assert/strict');const {createAutoReserve}=require('../lib/auto-reserve');
function setup(af={}) {
 let data={settings:{activeConnectionId:'a',autoFailover:{enabled:true,preferredPrimaryId:'a',poolConnectionIds:['b','c'],failThreshold:1,recoveryThreshold:1,strategy:'priority_order',autoReturn:true,...af}},connections:[{id:'a',name:'A'},{id:'b',name:'B'},{id:'c',name:'C'}]},version=0;
 const checks=[],switches=[],events=[];
 const dependencies={loadData:()=>structuredClone(data),saveData:d=>data=structuredClone(d),generation:()=>version,health:async c=>{checks.push(c.id);return {ok:c.id!=='a',latency:10};},activate:async(id,d,_u,guard)=>{guard();switches.push(id);d.settings.activeConnectionId=id;data=structuredClone(d);},history:e=>events.push(e)};
 return {dependencies,checks,switches,events,get data(){return data;},disable(){data.settings.autoFailover.enabled=false;version++;},engine:()=>createAutoReserve(dependencies)};
}
test('empty pool never implies all connections',async()=>{const h=setup({poolConnectionIds:[]});await h.engine().tick();assert.deepEqual(h.checks,['a']);assert.deepEqual(h.switches,[]);});
test('priority strategy stops after first healthy candidate',async()=>{const h=setup();await h.engine().tick();assert.deepEqual(h.checks,['a','b']);assert.deepEqual(h.switches,['b']);assert.equal(h.events.length,1);});
test('disable during in-flight health check cancels activation and runtime writes',async()=>{const h=setup();let release;h.dependencies.health=()=>new Promise(r=>release=r);const pending=h.engine().tick();h.disable();release({ok:false});await assert.rejects(pending,/отменена/);assert.deepEqual(h.switches,[]);assert.equal(h.data.settings.autoFailover.enabled,false);});
test('failed reserve switches to next candidate even without automatic return',async()=>{const h=setup({autoReturn:false});h.data.settings.activeConnectionId='b';h.dependencies.health=async c=>{h.checks.push(c.id);return {ok:c.id==='c',latency:10};};await h.engine().tick();assert.deepEqual(h.checks,['b','c']);assert.deepEqual(h.switches,['c']);});
test('primary is restored only after recovery threshold',async()=>{const h=setup({recoveryThreshold:2});h.data.settings.activeConnectionId='b';h.dependencies.health=async()=>({ok:true,latency:5});const engine=h.engine();await engine.tick();assert.deepEqual(h.switches,[]);engine.reset();await engine.tick();assert.deepEqual(h.switches,['a']);});
test('activation failure produces no success event or backup state',async()=>{const h=setup();h.dependencies.activate=async()=>{throw Error('failed restart');};await assert.rejects(h.engine().tick());assert.deepEqual(h.events,[]);assert.equal(h.data.settings.activeConnectionId,'a');});
test('rotation advances past unavailable candidates under a bounded time budget',async()=>{const h=setup({strategy:'lowest_ping'});let clock=0;h.dependencies.now=()=>clock;h.dependencies.health=async c=>{h.checks.push(c.id);clock+=30000;return {ok:c.id==='c',latency:10};};const engine=h.engine();await engine.tick();assert.deepEqual(h.switches,[]);engine.reset();await engine.tick();assert.deepEqual(h.switches,['c']);});
